### ISSUE TITLE
Add TiDB single sandbox support

### ISSUE THREAD

**Issue by morgo** [datacharmer/dbdeployer#54]
**Is your feature request related to a problem? Please describe.**

I would like to propose `single` sandbox support for TiDB, to allow developers to easily test compatibility without having to install a full distributed system (tidb+tikv+pd).

**Describe the solution you'd like**

TiDB can run with something called `mocktikv` (goleveldb) instead of `tikv`, which means that only one server component needs to be setup.  In my own testing it is 5x slower than `tikv`, but the advantage is that you only need a `tidb-server` setup, and no `pd` or `tikv`.

The memory footprint is smaller than MySQL, so it's possible some might even prefer it for development.

**Describe alternatives you've considered**

I've looked at alternatives installation methods like Homebrew etc, but they do not solve the use case of having multiple versions installed concurrently.  The TiDB release schedule is every 6 months, so dbdeployer is really useful in providing a system of organizing binaries for TiDB developers.

**Additional context**

I have looked at the initial work, and much of it can be implemented by sandbox templates and some core changes that @datacharmer already has planned (discussed at FOSDEM).  Let me try and comment in terms of each:

## Core
- [x] Requires support for detecting TiDB flavor https://github.com/datacharmer/dbdeployer/issues/53 https://github.com/datacharmer/dbdeployer/issues/52
- [x] Requires support for unnumbered tarballs https://github.com/datacharmer/dbdeployer/issues/51
- [x] Requires support for `--client-from` (or similar) https://github.com/datacharmer/dbdeployer/issues/49
- [x] Requires support for 'capabilities' of which TiDB will be only single, with no gtids, binlog (initially), relay log, show log (initially, because there is no general log), add option, semisync, expose dd tables. https://github.com/datacharmer/dbdeployer/issues/50
- [x] Tarball inspection for files `lib/libmysqlclient.so` and `scripts/mysql_install_db` needs to be moved into either "capabilities" or "flavors".

## Templates
I will send a pull request after some discussion, but my initial testing shows that the major template changes are:
- [init_db_template](https://github.com/morgo/dbdeployer-tidb-template/blob/master/template/single/init_db_template)
- [my_cnf_template](https://github.com/morgo/dbdeployer-tidb-template/blob/master/template/single/my_cnf_template)
- [status_template](https://github.com/morgo/dbdeployer-tidb-template/blob/master/template/single/status_template) * may need some discussion due to dependency
- [start_template](https://github.com/morgo/dbdeployer-tidb-template/blob/master/template/single/start_template)
- [stop_template](https://github.com/morgo/dbdeployer-tidb-template/blob/master/template/single/stop_template)
- Change grants_template to be based on grants_template57 (TiDB has no_auto_create_user too)

TBD:
I think that these two templates can be kept vanila assuming support for `--client-from`  is added:
- `my_template`
- [use_template](https://github.com/morgo/dbdeployer-tidb-template/blob/master/template/single/use_template)

**Comment by datacharmer** [comment]
TODO: add a flavor+capability rule to prevent deploying replication sandboxes.

**Comment by morgo** [comment]
I believe it will also need to refuse to deploy if neither `$MYSQL_EDITOR` or `--client-from` is specified.  The load_grants template requires the client to be configured, so it can't be deferred till later.

**Comment by datacharmer** [comment]
I am about to commit the check that will prevent replication, or a deployment without `--client-from`.
I will also make sure that template names are unique across collections.

I've noticed that  when I deploy several TiDB sandboxes, the server UUID is always the same(`d530594e-1c86-11e5-878b-6b36ce6799ca`), and also the variable `datadir` is always `/usr/local/mysql/data/`. Are they known issues?

**Comment by morgo** [comment]
Yes.  TiDB traditionally has _lied_ about variables it doesn't support.  We are moving away from this behavior though, and I have proposals to [cleanup sysvars](https://github.com/pingcap/tidb/issues/8895) and define [compatibility criteria](https://github.com/pingcap/tidb/issues/8949):

* `datadir` doesn't make sense for TiDB in the typical case (using tikv for storage).  But it makes sense for when using `mocktikv` as we are here.
* The server UUID does not apply to TiDB.  Each tidb server is stateless, membership-less and not special :-)

**Comment by datacharmer** [comment]
The implementation is almost finished. To complete it, I'd like to make TiDB installations compatible with MySQL, so that I can include a TiDB deployment in the functional test suite (currently I only have a mock test).

What's missing for integration:
* `test_sb`:
  * Ability to show the server port (currently it always shows 3306)
  * Ability of detecting whether the server is running. Current implementation uses the PID file. We can overwrite the template to use the socket instead. I am open to suggestions
* `status`:
  * show an on/off message as it happens for other deployments.

**Comment by morgo** [comment]
I have created https://github.com/pingcap/tidb/issues/9362 for the port issue and assigned myself.

I didn't think to use socket, but that makes sense to me.  Should we also clean up the startup script to delete a stale socket file if there is no tidb-server process to match it?  The alternative is to print a warning saying stale socket file.

**Comment by datacharmer** [comment]
Cleaning up the start is a good idea. 
If tidb-server were able to produce a PID file (with a `--pid` option) we could reuse the same scripts already in place for MySQL, or at least part of them.

**Comment by morgo** [comment]
I think you are right - TiDB should produce a pid file. I have created https://github.com/pingcap/tidb/issues/9379 to track.

It touches a few more server components, so it might take 1-2 weeks to write and merge.  Is that ok?

**Comment by datacharmer** [comment]
No pressure. What’s in the current code is good enough for now. I will merge it as it is.
When we have an improvement, we can open a PR to integrate

**Comment by morgo** [comment]
I looked into this.  It is not technically `mysqld` that offers pidfile support, but `mysqld_safe`.  See https://github.com/datacharmer/dbdeployer/pull/64

Please note that there is also a bug in my implementation of showing an accurate port.  It will be fixed in https://github.com/pingcap/tidb/pull/9383

**Comment by morgo** [comment]
This has been added to dbdeployer 1.19.0
